name: Check broken links in docs

on:
  pull_request:
    branches:
      - master

jobs:
  check-broken-links-in-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
            path: .lycheecache
            key: cache-lychee-${{ github.sha }}
            restore-keys: cache-lychee-
      - name: Check links in docs/*.md
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # Notes:
          # - Do not use `--base`.  All relative URLs in Markdown are based on the file itself.
          # - Verbosity level 2 enables debug logs and shows redirections. \
          # - Exclude dl.acm.org because it responses 403. \
          args: |
            --accept '200..=204,429,500' \
            --verbose --verbose \
            --no-progress \
            --cache \
            --max-cache-age 1d \
            --exclude 'https://users.cecs.anu.edu.au/~steveb/pubs/papers/**' \
            --exclude 'https://dl.acm.org/**' \
            './docs/**/*.md'
      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
            path: .lycheecache
            key: ${{ steps.restore-cache.outputs.cache-primary-key }}
