name: JikesRVM Performance Baseline

on:
  # Manual dispatch
  workflow_dispatch:
  # Or on every sunday 1200am UTC
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  jikesrvm-baseline:
    runs-on: [self-hosted, Linux, freq-scaling-off]
    # Allow 1 day to run
    timeout-minutes: 1440
    steps:
      - name: Checkout JikesRVM Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-jikesrvm
          path: mmtk-jikesrvm
          submodules: true
      # checkout perf-kit
      - name: Checkout Perf Kit
        uses: actions/checkout@v2
        with:
          repository: mmtk/ci-perf-kit
          ref: "0.6.0"
          path: ci-perf-kit
          submodules: true
      # setup
      - name: Setup
        run: |
          ./ci-perf-kit/scripts/history-run-setup.sh
          sed -i 's/^mmtk[[:space:]]=/#ci:mmtk=/g' mmtk-jikesrvm/mmtk/Cargo.toml
          sed -i 's/^#[[:space:]]mmtk/mmtk/g' mmtk-jikesrvm/mmtk/Cargo.toml
      # run
      - name: Performance Run
        timeout-minutes: 1440
        run: |
          export RESULT_REPO=mmtk/ci-perf-result
          export RESULT_REPO_BRANCH=self-hosted
          export RESULT_REPO_ACCESS_TOKEN=${{ secrets.CI_ACCESS_TOKEN }}
          export FROM_DATE=2020-07-10
          JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 ./ci-perf-kit/scripts/jikesrvm-stock.sh ./mmtk-jikesrvm/repos/jikesrvm
